### ISSUE TITLE
Empty response for RPC "blockchain.address.get_balance"

### ISSUE THREAD

**Issue by kamk** [spesmilo/electrum-server#100]
When I query about an address which hasn't been used yet (no TX in blockchain or mempool), the response is usually empty but sometimes it's valid JSON string:

`curl -v -d '{"method":"blockchain.address.get_balance","params":["1HEbGvJtr48uouAUuuUquXWTqXe1GgW4m5"],"id":1}' http://<electrum-server>:8081`

returns most of the time:
```
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.3 Python/2.7.9
< Date: Thu, 09 Jul 2015 13:45:00 GMT
< Set-Cookie: SESSION=4FUrB7ACfusrH1HqSvBgEXxLXa1d
< Content-type: application/json-rpc
< Access-Control-Allow-Origin: *
< Content-length: 0
```

and sometimes (approx. 1 in 10 tries) gives valid response: `{"id": 1, "result": {"confirmed": 0, "unconfirmed": 0}}`

**Comment by ecdsa** [comment]
that's normal. the protocol is asynchronous, it waork with polling
