### ISSUE TITLE
stratum_tcp stopped accepting connections after TypeError exception

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum-server#101]
Stratum TCP stopped accepting connections while catching up 5 blocks and lots of connections (possibly unrelated) - I had to restart to get stratum_tcp to work again. 

There was an exception which I couldn't find in the log but on the stderr
http://pastebin.com/NeLGxHN1

"TypeError: 'int' object is not subscriptable" looks as though some illegal command with an integer (?) was passed but the try: didn't return correctly but thew an exception.

**Comment by ecdsa** [comment]
fixed in e6df20b2766a33972eef5d06ab92a59792d5796b
