### ISSUE TITLE
SSL cert change breaks connection for clients who connected before with the older cert

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum-server#113]
Reinstalled my server and didn't have backups for the SSL cert and private key. The server is running, connects to IRC but I couldn't connect to it from my Electrum 2.3.2 client it until I manually deleted the old SSL data in /electrum-data/certs related to this server.

Server log file was saying:
handshake failure:[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:581)

Also, foundry server-peer-hash isn't able to connect to it and check server's hash via SSL port.

**Comment by ecdsa** [comment]
That's what SSL certs are for...
If you use a self signed cert, the client is going to trust the first cert is sees.
Use a CA signed cert if you don't want to be able to update your server certificate

**Comment by EagleTM** [comment]
The "fix" here is to use a different subdomain. I believe the other option might be to get a 3rd party certificate from a CA in the trust store of the OS. Those are treated with priority over the cached certs as far as I recall.
I'll close this issue as "won't fix"
