### ISSUE TITLE
Server Uses Excessive CPU Power

### ISSUE THREAD

**Issue by tl121** [spesmilo/electrum-server#121]
On a Ubutntu 14.04 machine with 8 GB RAM and an SSD, I observe that Electrum Server uses much more CPU time than bitcoind.  With normal network load, accumulated CPU time (measured by TOP) is at least 3 times that of Bitcoin core.  With large blocks, this can be 9 times greater.  In some cases, I have observed server logs that showed Electrum taking over 60 minutes to process one block.

The symptoms of server overload under high network load is that the server lags.   When the blocksize increases there is likely to be a serious problem even with servers running on fast machines, calling into question the viability of Electrum.

As a first step, an analysis of Electrum performance is needed. Other related performance problems are the very long time needed for server shutdown, increasing the likelihood of database corruption.

**Comment by SuBPaR42** [comment]
What CPU is on the server (you fail to mention that)?

**Comment by tl121** [comment]
1.4 GHz, single core, Haswell ATOM.  Note:  I deliberately chose a slow processor, because I wanted to see what would happen in the future should traffic and block sizes increase. This is a private server and needs essential zero bandwidth to handle users.  All it needs to do is to track the blockchain.

**Comment by ryanjohns** [comment]
I notice similar problems on an older server that I run privately as well. It is a 2.66GHz core 2 duo (E6750) with 4GB RAM. It often lags several blocks behind the tip and will not be able to catch up until activity on the bitcoin network goes down below some threshold. Bitcoin Core however has absolutely no trouble keeping up and uses very little CPU and the server is doing absolutely nothing besides running bitcoind and electrum-server.

The increased likelihood of database corruption that @tl121 mentioned is a real problem and it affects me regularly. If I have to reboot my server due to kernel updates or whatever, I often end up with a corrupted database and have to re-download from foundry and catch back up. I've tried various approaches to reducing this like tailing the logs and only stopping electrum once it finishes processing a new block but it doesn't seem to really help.

**Comment by SuBPaR42** [comment]
@tl121 :: There is your issue - that CPU is not beefy enough to run electrum-server.  It is fine for running bitcoind but the block processing of the server is single threaded and CPU intensive.
@ryanjohns :: You need to run 'electrum-server stop' and wait for the server to stop and exit cleanly before a reboot.  I haven't had a DB issue in almost 9 months.

**Comment by tl121** [comment]
The extant electrum-server code is pathetically inefficient, because it has an easier job to do that bitcoind and manages to use more CPU time to do so.  The database software is pathetically disorganized, otherwise there would not be data corruption in the face of many crashes. Techniques for dealing with these problems have been known since the early 1970's.

If bitcoin manages to survive the block-size controversy and continues to exist, then the existing electrum software will have to be upgraded otherwise it will only be a matter of time before its performance will be inadequate on the fastest available processors.

This performance problem has been built into electrum from the very beginning.  What bothers me most is that after some years nothing has been done to even acknowledge the existence of this problem.

**Comment by SuBPaR42** [comment]
I think eveyone is aware the server code needs a serious overhaul.  I am running jelectrum now to try and help fireduck build an alternative to the existing server software.  Thomas has been more focused on the client and now we need someone to help advance the server side.

**Comment by tl121** [comment]
OK, that's good to hear.  I was being harsh just to raise attention to the problem and if this is known, then there is no need to keep harping. 

I saw fireduck's post on the other thread.  It looks interesting and I might try it, but the only free machine that I have for experimentation is a few years old and has only 1 GB.  I have lots of 1.5 TB hard drives lying around, so storage is no problem for this machine, unlike my present electrum server machine that runs on a limited amount of SSD storage.

**Comment by SuBPaR42** [comment]
Yes - jelectrum loves RAM (I had to move to 12GB) as fireduck utilizes caches aggressively to help with speed.

**Comment by ryanjohns** [comment]
@SuBPaR42 Yeah I definitely do that before rebooting but I still run into problems occasionally. Had been running strong for 3-4 months until a kernel update yesterday and had to re-download. At least now I know about it via this handy monitoring tool I saw on reddit. Thanks

https://1209k.com/bitcoin-eye/ele.php
https://www.reddit.com/r/Electrum/comments/3hrf3r/selfservice_electrum_server_monitoring_tool/

**Comment by ecdsa** [comment]
I found that clients reconnecting after timeout were causing the request queue to grow too much.
it should be fixed by e168d24a93686955187e859f022e208834fe70fe

**Comment by ecdsa** [comment]
note: you can check the queue length with this command:

```
su electrum -c "./run_electrum_server debug chain_proc.queue.qsize\(\)"
```

**Comment by EagleTM** [comment]
server code is a lot more robust against db corruption now. I've had it recover from various hard crashes without a wrong hash.

Major performance increases are unlikely with the current code. a threaded approach like jelectrum may be the future. I don't think we shouldkeep it as an issue here and will close for now
