### ISSUE TITLE
blockchain.address.get_balance takes array of strings but only works with 1 argument

### ISSUE THREAD

**Issue by lclc** [spesmilo/electrum-server#143]
The blockchain.address.get_balance method takes a array as argument, but it only works with 1 address.

I'd expect it to be one of the following:

 - A) Change it to take a single string (1 address)
 - B) Take a array of addresses, return the sum of all balances
 - C) Take a array of addresses, return an array of structs with confirmed / unconfirmed balance

Example with Python and Java implementation of the server:

**telnet ecdsa.net 50001 (Python Electrum-Server)**

Request (1 address as array):

    { "id": 1, "method":"blockchain.address.get_balance", "params":["121pXWjzjpGqmxKt91jPgMbNrDFxFxtd12"] }

Response:

    {"id": 1, "result": {"confirmed": 8500000, "unconfirmed": 0}}

Request (2 addresses as array):

    { "id": 1, "method":"blockchain.address.get_balance", "params":["121pXWjzjpGqmxKt91jPgMbNrDFxFxtd12", "1EyBT13Ua4pAruuHSobh7AkLnSnKHBvj8x"] }

Response:

    {"id": 1, "result": {"confirmed": 8500000, "unconfirmed": 0}}

Request (1 address as string):

    { "id": 1, "method":"blockchain.address.get_balance", "params":"121pXWjzjpGqmxKt91jPgMbNrDFxFxtd12" }

Response:

    {"id": 1, "error": "startswith first arg must be str, unicode, or tuple, not NoneType"}

**telnet b.1209k.com 50001  (jElectrum-Server)**

Request (1 address as array):

    { "id": 1, "method":"blockchain.address.get_balance", "params":["121pXWjzjpGqmxKt91jPgMbNrDFxFxtd12"] }

Response:

    {"id":1,"result":{"transactions":1,"confirmed":8500000,"unconfirmed":0}}

Request (2 addresses as array):

    { "id": 1, "method":"blockchain.address.get_balance", "params":["121pXWjzjpGqmxKt91jPgMbNrDFxFxtd12", "1EyBT13Ua4pAruuHSobh7AkLnSnKHBvj8x"] }

Response:

    {"id":1,"result":{"transactions":1,"confirmed":8500000,"unconfirmed":0}}

Request (1 address as string):

    { "id": 1, "method":"blockchain.address.get_balance", "params":"121pXWjzjpGqmxKt91jPgMbNrDFxFxtd12" }

Response:

    {"id":1,"error":"Exception: org.json.JSONException: JSONObject[\"params\"] is not a JSONArray."}

In the protocol documentation: http://docs.electrum.org/en/latest/protocol.html#blockchain-address-get-balance

I'd vote for option A and keep the existing implementation (for backwards compatibility).
ping @fireduck64 

Also, standardized error codes would be nice to have one day :)

**Comment by lclc** [comment]
Updated to use 121pXWjzjpGqmxKt91jPgMbNrDFxFxtd12 instead of 1NS17iag9jJgTHD1VXjvLCEnZuQ3rJDE9L .

I took 1NS17iag9jJgTHD1VXjvLCEnZuQ3rJDE9L from the protocol documentation. According to Blockchain.info (and jElectrum / bitcoinj) it's not a valid address: https://blockchain.info/address/1NS17iag9jJgTHD1VXjvLCEnZuQ3rJDE9L

But the Electrum-Server (Python) returns {"id": 1, "result": {"confirmed": 90085203083, "unconfirmed": 0}} when asking for the balance of that address.

**Comment by lclc** [comment]
Seems to be the same for all the following methods (according to the protocol doc, didn't test):
  blockchain.address.subscribe
blockchain.address.get_history
blockchain.address.listunspent
blockchain.transaction.get
(and maybe more of those that aren't documented).

**Comment by lclc** [comment]
Just found this in the JSON-RPC. So it's actually the way the standard defines. B or C would still be an option, or otherwise adding a note in the docs :)

>4.2 Parameter Structures
If present, parameters for the rpc call MUST be provided as a Structured value. Either by-position through an Array or by-name through an Object.

>by-position: params MUST be an Array, containing the values in the Server expected order.

>by-name: params MUST be an Object, with member names that match the Server expected parameter names. The absence of expected names MAY result in an error being generated. The names MUST match exactly, including case, to the method's expected parameters.

**Comment by fireduck64** [comment]
Lucas, would you be interested in developing a test suite that tests
electrum server implementations for this sort of thing?

I'd like to keep them consistent and I'm happy to implement any changes we
can agree on.

**Comment by ecdsa** [comment]
closing.
