### ISSUE TITLE
Open assets

### ISSUE THREAD

**Issue by off-bank** [spesmilo/electrum-server#152]
How to configure electrum to show open assets?

**Comment by bauerj** [comment]
assets?

**Comment by off-bank** [comment]
Open source open assets on top of the blockchain, as used by NASDAQ, coinprism, blockcypher https://github.com/OpenAssets

**Comment by bauerj** [comment]
It seems like the protocol is not implemented in electrum.

**Comment by EagleTM** [comment]
This is not part of was electrum does. electrum is Bitcoin only for the time being.
