### ISSUE TITLE
server just freezes with no log messages. how to debug?

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum-server#169]
Hello,
Debian Jessie, 16GB of RAM, 2 CPU Cores, SSD. Bitcoin Core 0.13.0. Everything works good excepts it freezes from time to time (~1 week or 10 days) at a given block. It just stays like this (getinfo reports running, except it stays at the same block height and number of sessions decreases from few hundred to 0). This is a virtual machine, no custom kernel (using defaults).

This happens while:
- there is absolutely nothing in electrum.log (except the usual expected messages such as sent tx <txid>, processed block <number>, etc).
- Bitcoind is running unaffected.
- Swap space is not even close to full
- CPU/RAM are not under high usage
- Everything else on the server works fine
- The limits for the user running electrum-server are soft: 65536; hard 65536 reported by ulimit -Hn ; ulimit -Sn.

How can I debug this further? Can I log more in electrum.log? I want to see why it freezes suddenly. I guess it happens when there are too many sessions? The limit is 10000 utxo per address and sometimes I see over 400 sessions, can this be a reason?

**Comment by shsmith** [comment]
Are you on latest electrum-server? 
Older versions could throw exceptions that do not get logged (only visible when you manually run_electrum_server in a console)
Latest version logs all exceptions.
Most likely there is an unhandled exception that kills the block processor thread. 
See https://github.com/spesmilo/electrum-server/issues/132

**Comment by gits7r** [comment]
@shsmith yes I am on latest electrum-server but nothing in logs. Should I run it manually in a console with screen better? Maybe we can find out more information.

How can we fix unhandled exceptions that kill the block processor thread?

**Comment by shsmith** [comment]
It is worth a try. Launch run_electrum_server in a console and then wait for it to stop working. The console may contain a stack trace of the exception. Once you have a stack trace, post it here and the developers can fix it.

**Comment by gits7r** [comment]
Ok, so here we are. Server got jammed again. I am running it with screen run_electrum_server.py.

The console output says exactly nothing, besides the usual stuff:

[15/09/2016-15:33:07] mempool_update 1.48244214058 14618 23712
[15/09/2016-15:33:19] mempool_update 1.4087100029 14645 23778
[15/09/2016-15:33:26] SSL    <scrubbed>:50717    1 2.6.4
[15/09/2016-15:33:31] mempool_update 1.84341812134 14667 23835
[15/09/2016-15:33:37] SSL    <scrubbed>:61756    1 2.5.4
[15/09/2016-15:33:42] mempool_update 1.80578303337 14686 23893
[15/09/2016-15:33:54] mempool_update 1.54178118706 14717 23975
[15/09/2016-15:34:06] mempool_update 1.4765188694 14746 24052
[15/09/2016-15:34:17] mempool_update 1.53996920586 14773 24136
[15/09/2016-15:34:29] mempool_update 1.57358694077 14808 24225
[15/09/2016-15:34:40] mempool_update 1.47407102585 14839 24317
[15/09/2016-15:34:50] SSL     <scrubbed>:38110    1 2.6.4
[15/09/2016-15:34:52] mempool_update 1.42013692856 14862 24382
[15/09/2016-15:34:52] SSL  <scrubbed>:46953    1 2.6.3
[15/09/2016-15:34:54] SSL    <scrubbed>:59890    1 2.5.4
[15/09/2016-15:35:09] SSL        <scrubbed>:4138    1 2.6.4
[15/09/2016-15:35:10] SSL    <scrubbed>:60085    1 2.6.4
[15/09/2016-15:35:16] SSL    <scrubbed>:19424    1 2.6.3
[15/09/2016-15:35:26] TCP   <scrubbed>:33801    1 2.6.4

electrum-server getinfo reports:
{
    "blocks": 429968,
    "cached": 20711,
    "peers": 49,
    "sessions": 19,
    "watched": 0
}

Bitcoind is running and is at block 430144.
If I try to connect to my server from electrum wallet it says Synchronizing... for very long time, disconnect and again Synchronizing... something like an endless loop. It doesn't drop the server it just stays in Synchronizing ... position.

What can I do to find out why this happens? It's the 7th time consecutively (once every about 8-9 days).

**Comment by shsmith** [comment]
not sure if this is related or not, but occasionally my electrum-server "virt" will grow from a normal 5000-7000 to over 14000 followed by the session count dropping (due to lag, I assume). 
to work around this, I'm running a cron job that checks the size of the process and restarts it when > 10000. 
maybe something similar would help you. 
see http://pastebin.com/mr3i2skE

**Comment by gits7r** [comment]
@shsmith I don't know currently the server is jammed but it uses 12,7% from the RAM memory and 5,6% from CPU, and the swap space is at 28% usage on the entire server. The fact that the logs don't say anything is annoying. Also, I can't stop the server -- electrum-server stop or interrupt signal just freeze the same, only way is to entirely reboot the server.

If the size of the process is the problem here, the script should be coded in electrum-server itself, and behave by default like this so it doesn't become useless when run unattended. Don't you think?

I will try to run it with dir(BlockchainProcessor) and see if we find out more info.

**Comment by shsmith** [comment]
there is a small possibility it is hung in the rpc interface to bitcoind. before you reboot, try restarting bitcoind to see it that causes some reaction in electrum-server.

**Comment by gits7r** [comment]
Bitcoind seams to be growing in blocks ... and in connections with peers. So i guess it's in electrum-server.

**Comment by gits7r** [comment]
Also, can't run it in debug mode. run_electrum_server.py debug "dir(BlockchainProcessor)" outputs: server not running.

**Comment by shsmith** [comment]
you use the debug command after starting the server normally. it uses rpc to query the running server.  what happened when you restarted bitcoind? probably nothing, but worth a try in case it was stuck on some transient error it never recovered from.

**Comment by shsmith** [comment]
Hopefully when ThomasV is caught up with the client release he will focus a bit of time on server improvements. Electrum user base seems to be growing and server infrastructure is weak.

**Comment by gits7r** [comment]
I think I have a problem in running debug. Here is what output I get when running the command (after server already started):

run_electrum_server.py debug "dir(BlockchainProcessor)"
['_Thread__bootstrap', '_Thread__bootstrap_inner', '_Thread__delete', '_Thread__exc_clear', '_Thread__exc_info', '_Thread__initialized', '_Thread__stop', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_block', '_note', '_reset_internal_locks', '_set_daemon', '_set_ident', 'add_request', 'bitcoind', 'block2header', 'catch_up', 'close', 'daemon', 'deserialize_block', 'do_catch_up', 'do_subscribe', 'do_unsubscribe', 'flush_headers', 'getName', 'get_block', 'get_chunk', 'get_header', 'get_history', 'get_mempool_transaction', 'get_merkle', 'get_status', 'get_unconfirmed_history', 'get_unconfirmed_value', 'hash_header', 'ident', 'import_block', 'init_headers', 'invalidate_cache', 'isAlive', 'isDaemon', 'is_alive', 'join', 'main_iteration', 'memorypool_update', 'name', 'pop_header', 'print_time', 'process', 'push_response', 'read_chunk', 'read_header', 'run', 'setDaemon', 'setName', 'set_time', 'start', 'wait_on_bitcoind', 'write_header']

**Comment by gits7r** [comment]
I think I have a problem in running debug. Here is what I get when I run the command after server already running:

 run_electrum_server.py debug "dir(BlockchainProcessor)"
['_Thread__bootstrap', '_Thread__bootstrap_inner', '_Thread__delete', '_Thread__exc_clear', '_Thread__exc_info', '_Thread__initialized', '_Thread__stop', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_block', '_note', '_reset_internal_locks', '_set_daemon', '_set_ident', 'add_request', 'bitcoind', 'block2header', 'catch_up', 'close', 'daemon', 'deserialize_block', 'do_catch_up', 'do_subscribe', 'do_unsubscribe', 'flush_headers', 'getName', 'get_block', 'get_chunk', 'get_header', 'get_history', 'get_mempool_transaction', 'get_merkle', 'get_status', 'get_unconfirmed_history', 'get_unconfirmed_value', 'hash_header', 'ident', 'import_block', 'init_headers', 'invalidate_cache', 'isAlive', 'isDaemon', 'is_alive', 'join', 'main_iteration', 'memorypool_update', 'name', 'pop_header', 'print_time', 'process', 'push_response', 'read_chunk', 'read_header', 'run', 'setDaemon', 'setName', 'set_time', 'start', 'wait_on_bitcoind', 'write_header']

**Comment by shsmith** [comment]
i've been poking around and trying to read along in the blockchain_processor.py to look for things that might be of interest to the lockup.

The blockchain processor instance is here:
`run_electrum_server.py debug "dir(chain_proc)"
`

And dumping a few variables from a server that is running normally:
```
bitcoin@electrumd:~$ run_electrum_server.py debug "str(chain_proc.start_catchup_height)"
430305
bitcoin@electrumd:~$ run_electrum_server.py debug "str(chain_proc.up_to_date)"
True
bitcoin@electrumd:~$ run_electrum_server.py debug "str(chain_proc.sent_height)"
430305
```
If it is stuck in the catch_up method, you might see up_to_date = False

Unfortunately, most of the interesting variables in catch_up() and memorypool_update() are locals. I don't think we can query those this way.

**Comment by shsmith** [comment]
this will check if your communication with bitcoind is alive:
run_electrum_server.py debug "str(chain_proc.bitcoind('getblock', (chain_proc.storage.last_hash,)))"
that is what happens at the top of do_catch_up
mine prints a giant json blob. 

it is possible the whole chain_proc thread has exited. not sure how to detect that, but maybe this will:
run_electrum_server.py debug "str(chain_proc.is_alive())"
run_electrum_server.py debug "str(chain_proc.isAlive())"

**Comment by gits7r** [comment]
Thanks for your assistance in this @shsmith . So here is what happened today: the server was running fine, up to date with bitcoind, with 196 current sessions and the log was indicating that is working (sending txes, mempool updates, etc.). So there was nothing wrong, but I've run your high-mem script anyway. And it said: OVERLOAD: Restarting electrum. 

So, why did it detect it's overloaded while it was running fine? My guess is that the script knows what its doing, and it restarted it to prevent further jams - but if this is the case why don't we hardcode that script in electrum itself, so users who don't know about it and want to run servers unattended are protected against this? What do you think?

**Comment by shsmith** [comment]
My guest guess is that certain clients have imported super active public addresses, like those seen here: https://blockchain.info/popular-addresses. When one of those clients connects, it fills up memory with millions of transactions and bogs down the server. I agree the server should be hardened to better handle this sort of thing. The server performs well with "normal" user use cases.

**Comment by gits7r** [comment]
@shsmith we have limited the max utxos we return for an address in commit d1501bfe0c278304d2bd7d90967a333935044b16 -- the limit is set to 1000. So why this problem still occurs?

I have just opened issue 1930 to handle the client side part of this problem. Do you have time to hardcode this protection directly into electrum-server? Do we have any other option besides restarting the server entirely? Because it losses all the sessions and disconnects everybody for few seconds.

**Comment by ecdsa** [comment]
@gits7r: the code has a hard coded limit of 1000 UTXOs per address
the limit that is configurable is not about unspent TXOs, it is about spent TXOs.
(you reported that "The limit is 10000 utxo per address", I belive you are confused)

**Comment by gits7r** [comment]
@ecdsa True, I mean we need to code the server to return an error if/when both limits are reached (spent TXOs of an address or UTXOs which is currently hardcoded to 1000) and disconnect the client who goes beyond these limits, and the client to interpret that error code returned by the server such as it will display a clear notification that the wallet balance and history may not be accurate and don't try to reconnect again to that server or other server. I am fine with the hardcoded limits -- if someone has a private key containing more than 1000 UTXOs they should choose something else than electrum which is not SPV -- we just need to return an error from the server when either of the limits are reached and correctly interpret it in the client.

**Comment by gits7r** [comment]
Now back to the purpose of this ticket which we need to take care of, @shsmith @ecdsa 
It happened again. Right now my server is jammed. 

- checked connection with bitcoind by running:
# run_electrum_server.py debug "str(chain_proc.bitcoind('getblock', (chain_proc.storage.last_hash,)))"
and it returns a giant json blob as it should.

- checked if the block processor thread is dead by running:
# run_electrum_server.py debug "str(chain_proc.is_alive())"
and it returns True

- checked the high-mem usage with your script and it doesn't restart like it's not overloaded, it returns this:
pid: 31193  VmSize:  6379mb  sessions:  17  SSL:                                                                                s 17/17  TCP: OK   0/0   TX:  51  load: 6.08 6.06 6.11 1/103 23886

bitcoind runs smoothly and it catches up (I am on the recommended recent version of bitcoind) while electrum-server is jammed for 2 days and has 10-12 sessions as opposite to 230-300.

What do you think?

**Comment by gits7r** [comment]
this is a hard bug to catch. I've run electrum-server stop to stop the jammed server and it froze and waiting until process $pid terminates... and when I tried again electrum-server getinfo I got this:

Session terminated, terminating shell...Traceback (most recent call last):
File "/usr/local/bin/run_electrum_server.py", line 4, in <module>
    __import__('pkg_resources').run_script('electrum-server==1.0', 'run_electrum_server.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
root@electrum:~#     self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/electrum_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_server.py", line 291, in <module>

  File "/usr/local/lib/python2.7/dist-packages/electrum_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_server.py", line 141, in run_rpc_command

  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
 ...terminated.

Does this help?

**Comment by gits7r** [comment]
Update: I left it running with the cronjob active to detect high mem and restart. This morning it became inaccessible even through SSH. The high script memory jammed the server entirely while trying to restart. I am investigating this also at upstream level (hypervisor) to check and see if I find out more information.

**Comment by gits7r** [comment]
@ecdsa @shsmith I have documented everything and gathered relevant logs. Please see here:

http://electrum-foundry.sky-ip.org/electrum-server-bug/index.html

**Comment by gits7r** [comment]
I am going to close this since I have identified a kernel panic upstream, at hypervisor level that sends no fatal error to electrum server inside the vm and just freezes it. Running on bare metal fixes it.
