### ISSUE TITLE
Install Electrum Server

### ISSUE THREAD

**Issue by AgenorZ** [spesmilo/electrum-server#189]
This is what happen when i use sudo ./configure

``Connecting with foundry.electrum.org (foundry.electrum.org)[78.46.103.75]:80... connect.``
``HTTP request sent, waiting for an answer ... 404 Not Found``
``2018-03-25 19:03:35 ERROR 404: Not Found.``

**Comment by bauerj** [comment]
This project is not maintained any more.

Please use kyuupichan/electrumx in stead.
