### ISSUE TITLE
Is it possible to do bulk payments using electrumX?

### ISSUE THREAD

**Issue by bumbumpaw07** [spesmilo/electrum-server#191]
Is it possible to do bulk/batch/mass payments like the available functionality in electrum client that allows users to export csv or input multiple lines for addresses?

https://electrum.readthedocs.io/en/latest/faq.html#can-i-do-bulk-payments-with-electrum

https://electrum.readthedocs.io/en/latest/_images/paytomany.png

**Comment by SomberNight** [comment]
This is not the repository for ElectrumX.
Also, the server is agnostic to the nature of bitcoin transactions being broadcast, so of course those can have multiple outputs. This is something the client needs to implement, and as you yourself have already pointed out, Electrum (the client) already supports this.
