### ISSUE TITLE
ulimit: open files: cannot modify limit: Operation not permitted

### ISSUE THREAD

**Issue by ixcoin123** [spesmilo/electrum-server#81]
Getting this error when starting electrum-server:

``` bash
$ electrum-server start
Starting server as daemon
/usr/local/bin/electrum-ixc-server: line 64: ulimit: open files: cannot modify limit: Operation not permitted
```

I'm running electrum-server on a Xen vps server... Might that be the issue? And if so, how to get around that problem?

**Comment by annaparker** [comment]
I'm experiencing the same problem on my OpenVZ VPS. How to run as root (as it's not supported)?

**Comment by abitfan** [comment]
See #104
