### ISSUE TITLE
Negative Balance

### ISSUE THREAD

**Issue by devktor** [spesmilo/electrum-server#88]
I got few times negative unconfirmed balance

request: <code>{ "id": 1, "method": "blockchain.address.get_balance", "params:["1ENgineCaw1zmJq2G2Gx1g9MAjjokGKu4K"] }</code></br>
result: <code> {"id": 1, "result": {"confirmed": 533506535, "unconfirmed": -35150000}}</code>

**Comment by ecdsa** [comment]
that's normal.
the actual balance is the sum of both
