### ISSUE TITLE
blockchain parsing information in log file during catch up

### ISSUE THREAD

**Issue by ser** [spesmilo/electrum-server#97]
When I download current leveldb from foundry, it is outdated. Unfortunately at the moment electrum server does not report progress of catching up to current blockchain, which is very annoying, as you are not able to see what's going on with the server for hours.

Request: the server should report to log file every parsed blockchain.

**Comment by kamk** [comment]
You can check current status by: `sudo electrum-server getinfo`

**Comment by SuBPaR42** [comment]
Log updates every 1000 blocks...

As noted, my preferred method is as @kamk mentions, use 'electrum-server getinfo'

**Comment by ser** [comment]
I would repeat my my suggestion, there is no single reason to hide processing blocks information, as during catch up electrum server is essentially not doing anything else than processing blocks.

**Comment by wozz** [comment]
I think the original reason for this was that when the chain is parsed from the beginning, printing every line is too fast to be useful.

**Comment by ecdsa** [comment]
@wozz that's correct
